#!/usr/bin/env bash

source "${HOME}/.config/sketchybar/variables.sh" # Loads all defined colors

# AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
# AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

# General bar and defaults
sketchybar --bar height=30 \
	color="${BAR_COLOR}" \
	shadow="${SHADOW}" \
	position=top \
	sticky=on \
	padding_right=0 \
	padding_left=0 \
	corner_radius=2 \
	y_offset=0 \
	margin=0 \
	blur_radius=20 \
	notch_width=200 \
	--default updates=when_shown \
	icon.font="${FONT}:Bold:14" \
	icon.color="${ICON_COLOR}" \
	icon.padding_left="${PADDINGS}" \
	icon.padding_right="${PADDINGS}" \
	label.font="${FONT}:Bold:14" \
	label.color="${LABEL_COLOR}" \
	label.padding_left="${PADDINGS}" \
	label.padding_right="${PADDINGS}" \
	background.padding_right="${PADDINGS}" \
	background.padding_left="${PADDINGS}" \
	popup.background.border_width=1 \
	popup.background.corner_radius=11 \
	popup.background.border_color="${POPUP_BORDER_COLOR}" \
	popup.background.color="${POPUP_BACKGROUND_COLOR}" \
	popup.background.shadow.drawing="${SHADOW}"

# Left
# source "$ITEM_DIR/spaces.sh"
source "${ITEM_DIR}/apple.sh"
source "${ITEM_DIR}/aerospace.sh"

# Center (of notch)
source "${ITEM_DIR}/front_app.sh"
source "${ITEM_DIR}/front_app_workspace.sh"

# Right
source "${ITEM_DIR}/clock.sh"
source "${ITEM_DIR}/calendar.sh"
source "${ITEM_DIR}/battery.sh"
source "${ITEM_DIR}/volume.sh"
source "${ITEM_DIR}/cpu.sh"
source "${ITEM_DIR}/input_source.sh"
source "${ITEM_DIR}/qq.sh"
source "${ITEM_DIR}/feishu.sh"
source "${ITEM_DIR}/tg.sh"
source "${ITEM_DIR}/wechat.sh"

#################### Finalizing Setup ####################
sketchybar --hotload true
sketchybar --update
echo "sketchybar configuration loaded.."
