[colors.bright]
black = "0x6e7681"
blue = "0x79c0ff"
cyan = "0x39c5cf"
green = "0x79c0ff"
magenta = "0xbc8cff"
red = "0xfdac54"
white = "0xb1bac4"
yellow = "0xe3b341"

[colors.cursor]
cursor = "0xc9d1d9"
text = "0x0d1117"

[colors.normal]
black = "0x484f58"
blue = "0x58a6ff"
cyan = "0x39c5cf"
green = "0x58a6ff"
magenta = "0xbc8cff"
red = "0xec8e2c"
white = "0xb1bac4"
yellow = "0xd29922"

[colors.primary]
background = "0x0d1117"
foreground = "0xc9d1d9"

[cursor]
style = "Block"

[font]
size = 18

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
blur = true
decorations = "none"
dynamic_padding = true
opacity = 0.75

[window.dimensions]
columns = 80
lines = 25

[window.padding]
x = 0
y = 2
